### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by MLFJBekker** [thefyfy/ScreenlyManager#2]
Hi, I've tried installing your app, but during installation i get "installation failed"
Reason:
Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

Can you help with this?

**Comment by thefyfy** [comment]
Hi, the better way is compilling the app with Visual Studio 2017 from sources. In this way, you'll have your proper certificate.

**Comment by MLFJBekker** [comment]
thanx for answering. sadly I don't have visual studio, nor would I know how to do this.
too bad, looked like a good solution

**Comment by mkimbrough** [comment]
Right click on APPX file
Click Properties
Click Digital Signatures
Select Signature from the list
Click Details
Click View Certificate
Click Install Certificate
Instead of installing the certificate in the current user's Store location, select "Local Machine"and then selected "Trusted Root Certification Authorities
